language: objective-c
osx_image: xcode10.2

xcode_workspace: FFPopup.xcworkspace
xcode_project: FFPopup.xcodeproj
xcode_scheme: FFPopup
podfile: Demo/Podfile

before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build as dynamic framework
  - xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

  - echo Build the Demo apps
  - xcodebuild build -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "FFPopup_Objc" -configuration Debug -destination 'name=iPhone X' | xcpretty -c
  - xcodebuild build -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "FFPopup_Swift" -configuration Debug -destination 'name=iPhone X' | xcpretty -c

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FFPopup'
